=encoding utf8

=head1 Captioned Image - “Every mighty Klingon Warrior”

=head2 About

This repository contains the sources for a captioned image. To view or
edit it type:

    inkscape ./Every-mighty-Klingon-Warrior.svg

To build type C<make> .

=head2 Image Credits

C<KlingonDeathRitual.jpg> taken from:
L<http://en.memory-alpha.org/wiki/Klingon?oldid=1647807> .

C<Sesame-Street--40th-dvd-booklet.jpg> taken from:
L<http://muppet.wikia.com/wiki/File:40th-dvd-booklet.jpg> .

=head2 Creator

L<http://www.shlomifish.org/> - Shlomi Fish.

=cut

